import type { ThemeDefinition } from 'vuetify';

export const lightTheme: ThemeDefinition = {
  colors: {
    primary: '#68548e',
    'surface-tint': '#68548e',
    'on-primary': '#ffffff',
    'primary-container': '#ebddff',
    'on-primary-container': '#230f46',
    secondary: '#635b70',
    'on-secondary': '#ffffff',
    'secondary-container': '#e9def8',
    'on-secondary-container': '#1f182b',
    tertiary: '#7e525d',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#ffd9e1',
    'on-tertiary-container': '#31101b',
    error: '#ba1a1a',
    'on-error': '#ffffff',
    'error-container': '#ffdad6',
    'on-error-container': '#410002',
    background: '#ffffff',
    'on-background': '#1d1b20',
    surface: '#fef7ff',
    'on-surface': '#1d1b20',
    // 'surface-variant': '#e7e0eb',
    'on-surface-variant': '#49454e',
    outline: '#7a757f',
    'outline-variant': '#cbc4cf',
    shadow: '#000000',
    scrim: '#000000',
    'inverse-surface': '#322f35',
    'inverse-on-surface': '#f5eff7',
    'inverse-primary': '#d3bcfd',
    'primary-fixed': '#ebddff',
    'on-primary-fixed': '#230f46',
    'primary-fixed-dim': '#d3bcfd',
    'on-primary-fixed-variant': '#4f3d74',
    'secondary-fixed': '#e9def8',
    'on-secondary-fixed': '#1f182b',
    'secondary-fixed-dim': '#cdc2db',
    'on-secondary-fixed-variant': '#4b4358',
    'tertiary-fixed': '#ffd9e1',
    'on-tertiary-fixed': '#31101b',
    'tertiary-fixed-dim': '#f0b7c5',
    'on-tertiary-fixed-variant': '#643b46',
    'surface-dim': '#ded8e0',
    'surface-bright': '#fef7ff',
    'surface-container-lowest': '#ffffff',
    'surface-container-low': '#f8f1fa',
    'surface-container': '#f2ecf4',
    'surface-container-high': '#ede6ee',
    'surface-container-highest': '#e7e0e8'
  }
};

export const darkTheme: ThemeDefinition = {
  colors: {
    primary: '#d3bcfd',
    'surface-tint': '#d3bcfd',
    'on-primary': '#38265c',
    'primary-container': '#4f3d74',
    'on-primary-container': '#ebddff',
    secondary: '#cdc2db',
    'on-secondary': '#342d40',
    'secondary-container': '#4b4358',
    'on-secondary-container': '#e9def8',
    tertiary: '#f0b7c5',
    'on-tertiary': '#4a2530',
    'tertiary-container': '#643b46',
    'on-tertiary-container': '#ffd9e1',
    error: '#ffb4ab',
    'on-error': '#690005',
    'error-container': '#93000a',
    'on-error-container': '#ffdad6',
    background: '#151218',
    'on-background': '#e7e0e8',
    surface: '#151218',
    'on-surface': '#e7e0e8',
    // 'surface-variant': '#49454e',
    'on-surface-variant': '#cbc4cf',
    outline: '#948f99',
    'outline-variant': '#49454e',
    shadow: '#000000',
    scrim: '#000000',
    'inverse-surface': '#e7e0e8',
    'inverse-on-surface': '#322f35',
    'inverse-primary': '#68548e',
    'primary-fixed': '#ebddff',
    'on-primary-fixed': '#230f46',
    'primary-fixed-dim': '#d3bcfd',
    'on-primary-fixed-variant': '#4f3d74',
    'secondary-fixed': '#e9def8',
    'on-secondary-fixed': '#1f182b',
    'secondary-fixed-dim': '#cdc2db',
    'on-secondary-fixed-variant': '#4b4358',
    'tertiary-fixed': '#ffd9e1',
    'on-tertiary-fixed': '#31101b',
    'tertiary-fixed-dim': '#f0b7c5',
    'on-tertiary-fixed-variant': '#643b46',
    'surface-dim': '#151218',
    'surface-bright': '#3b383e',
    'surface-container-lowest': '#0f0d13',
    'surface-container-low': '#1d1b20',
    'surface-container': '#211f24',
    'surface-container-high': '#2c292f',
    'surface-container-highest': '#36343a'
  }
};
